image: Visual Studio 2017

environment:
  
  matrix:
  - solution_path: Homework-Semester-2-/blob/ListGeneric/hw8/ListGeneric/ListGeneric.sln
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
