image: Visual Studio 2017

environment:
  
  matrix:
  - solution_path: Homework-Semester-2-/tree/ListGeneric/hw8/ListGeneric/List
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
