image: Visual Studio 2019

environment:
  
  matrix:
  - solution_path: hw8/ListGeneric/ListGeneric.sln
  - solution_path: hw2/StackBasedCalculator/StackBasedCalculator.sln  
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
